add tooltip
js-tasks-ru/htmlcss-20220120_valeriya-koroleva pull request #5
Opened 2022-02-03 17:00 UTC by Valeria2312

2022-02-03 17:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-09 17:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 18:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-15 11:05 UTC, GSemikozov requested changes

2022-02-15 11:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
это нужно просто чтобы выравнивать тултип на пустой хтмл странице с компонентом? Если да, то просто удаляем, это не будет переиспользоваться)

2022-02-15 11:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin-top: 50px;
на уровне блока не задаем марджины, да они в общем-то и так будут лишними - здесь они добавлены для того чтобы на пустой странице сделать отступ сверху под всплывашку, но на реальной странице при встраивании тултипа это не потребуется)

2022-02-15 11:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: calc(-200% - 3px);
жесткая привязка в высоте иконки относительно которой позиционируем; а что если иконка будет в 2 раза больше? тогда придется переписывать позиционирование и ставить например -400 ))
поэтому, надежнее будет так: bottom: calc(100% + /*высота стралки в пикселях*/) где 100% это собственно высота иконки

2022-02-15 11:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: -40%;
та же история что и с .tooltip__bubble, только здесь - top: 100%

2022-02-24 19:20 UTC, GSemikozov approved these changes

2022-02-24 19:20 UTC, merged